# Generated by Django 5.1.2 on 2024-10-26 02:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50, unique=True)),
                ('species', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('weight', models.FloatField()),
                ('health_status', models.CharField(max_length=100)),
                ('is_for_sale', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='GrowthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight', models.FloatField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_records', to='ganaderia.animal')),
            ],
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkup_date', models.DateField()),
                ('health_status', models.CharField(max_length=100)),
                ('medication_given', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='ganaderia.animal')),
            ],
        ),
        migrations.CreateModel(
            name='PastureZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area_size', models.FloatField()),
                ('grazing_capacity', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('current_animals', models.ManyToManyField(blank=True, related_name='zones', to='ganaderia.animal')),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='pasture_zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ganaderia.pasturezone'),
        ),
        migrations.CreateModel(
            name='SalePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_sale_date', models.DateField()),
                ('predicted_weight', models.FloatField()),
                ('market_price', models.FloatField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_predictions', to='ganaderia.animal')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temperature', models.FloatField()),
                ('rainfall', models.FloatField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('pasture_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_records', to='ganaderia.pasturezone')),
            ],
        ),
    ]
