# Generated by Django 5.1.2 on 2024-10-30 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ganaderia', '0003_fieldzone_map'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FieldZone',
        ),
        migrations.DeleteModel(
            name='Map',
        ),
    ]
